### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by vidit98** [vinits5/pcrnet_pytorch#1]
Thank you for making the code available. Could you please share the pretrained models?

**Comment by vinits5** [comment]
I will update the repository soon with the pre-trained model. Thanks for notifying me.

**Comment by vinits5** [comment]
Hey Vidit,

Appology for the delay.
I have added the pretrained model. 
Link: https://github.com/vinits5/pcrnet_pytorch/tree/master/pcrnet/pretrained/exp_ipcrnet/models
