### ISSUE TITLE
Running anything in this codebase in 2023

### ISSUE THREAD

**Issue by MikeGiuliani** [vinits5/pcrnet_pytorch#13]
I have spent so many hours trying to run anything at all in this codebase with no success. Endless conflicts, path issues, and dependency issues. The non-PyTorch PCRNet repo was even worse. Has anyone been able to actually get it working reasonably recently or is it inherently broken in some way?

**Comment by alejandroHdzV** [comment]
I got it to work (Sept, 2023)

**Comment by vinits5** [comment]
@MikeGiuliani can you please be more specific about the issue that you are facing? I would be happy to help you.

**Comment by staystupidstayfoolish** [comment]
> I got it to work (Sept, 2023)
can you please provide a requirement text?

**Comment by vinits5** [comment]
@staystupidstayfoolish, Thanks for updating everyone.
I will add requirement.txt file by the end of this week.
@MikeGiuliani, I am closing this issue due to lack of clarity in your error. Others have confirmed that the code is working.
