### ISSUE TITLE
facing dependency issue

### ISSUE THREAD

**Issue by staystupidstayfoolish** [vinits5/pcrnet_pytorch#14]
Can you provide a requirements.txt? I can't even run the test code successfully.

**Comment by vinits5** [comment]
https://github.com/vinits5/pcrnet_pytorch/blob/master/requirements.txt
Added requirements.txt file.

**Comment by staystupidstayfoolish** [comment]
> https://github.com/vinits5/pcrnet_pytorch/blob/master/requirements.txt Added requirements.txt file.
Thank you very much!
