### ISSUE TITLE
error when intalling dependencies using requirements.txt

### ISSUE THREAD

**Issue by staystupidstayfoolish** [vinits5/pcrnet_pytorch#16]
![Screenshot from 2024-03-22 21-03-01](https://github.com/vinits5/pcrnet_pytorch/assets/108455773/21c9ce48-dec6-441a-b7e4-32997bbc446c)
ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1)
ERROR: No matching distribution found for torch==1.4.0

**Comment by staystupidstayfoolish** [comment]
I change torch==1.4.0 to 1.13.1 and it works

**Comment by staystupidstayfoolish** [comment]
I edit the txt by delete some version specifications, but it doesn't work as well. bro, did you install dependencies using the requirements.txt you provided??

**Comment by vinits5** [comment]
@staystupidstayfoolish Thank you raising an issue.
I used torch==1.4.0 when I had developed this code but with the latest updates there are errors.
I have updated the requirements.txt file again and personally checked it on my local system. Please try again.

**Comment by staystupidstayfoolish** [comment]
it works this time. thank you very much.
