### ISSUE TITLE
Missing pointnet maxpool

### ISSUE THREAD

**Issue by ryanjustus** [vinits5/pcrnet_pytorch#2]
According to the paper and the tensorflow implementation I expected a max pool at the end of the PointNet embedding

**Comment by vinits5** [comment]
Hey,

For the sake of modularity. I have defined the max pool in the pcrnet class and not in pointnet class. 
Link: https://github.com/vinits5/pcrnet_pytorch/blob/master/pcrnet/models/pcrnet.py
Check this code. Here self.pooling is defined which is used for max pool at the end of PointNet embedding.
