### ISSUE TITLE
Results and metrics

### ISSUE THREAD

**Issue by abderraouf-guesmi-de** [vinits5/pcrnet_pytorch#3]
Hi  Vinit,
how i can find the metrics in the article(Table 1) from this code?

Thanks in advance,
Abderraouf

**Comment by vinits5** [comment]
Hey,

Sorry, I haven't included the script to evaluate the metrics in this repository. But, you can refer to function "find_errors" at https://github.com/vinits5/pcrnet/blob/master/results_PCRNet.py. This is a TensorFlow repository for PCRNet. 
Also, "log_test_results" will be a helpful function to store all the results. You can find it at https://github.com/vinits5/pcrnet/blob/master/helper.py

**Comment by abderraouf-guesmi-de** [comment]
Hi Vinit,

Where can I find results(Table 1:Rot_Error,Trans_Error,Time,AUC=0.99) in
https://github.com/vinits5/pcrnet/tree/master/plot_results.Do I have to
change parameters in itresults_PCRNet.py?

Thanks in advance,
Abderraouf
