### ISSUE TITLE
There is a mistake when I run the train_pcrnet.py

### ISSUE THREAD

**Issue by Yellowshuohahaha** [vinits5/pcrnet_pytorch#5]
Hi, vinits5. I meet some mistakes when I run the train_pcrnet.py. It notes that 'subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1'.  Do you know how can I solve it?

**Comment by Yellowshuohahaha** [comment]
It notes that 'subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1'.

**Comment by vinits5** [comment]
Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
The error is due to the version mismatch of Pytorch.
If the given link resolves the issue then, please let me know.

**Comment by Yellowshuohahaha** [comment]
> Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> The error is due to the version mismatch of Pytorch.
> If the given link resolves the issue then, please let me know.

Thank you very much! I will have a look.

**Comment by Yellowshuohahaha** [comment]
> Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> The error is due to the version mismatch of Pytorch.
> If the given link resolves the issue then, please let me know.

The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)

**Comment by shenqildr** [comment]
> > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > The error is due to the version mismatch of Pytorch.
> > If the given link resolves the issue then, please let me know.
> 
> The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)

I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.

**Comment by Yellowshuohahaha** [comment]
> > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > The error is due to the version mismatch of Pytorch.
> > > If the given link resolves the issue then, please let me know.
> > 
> > 
> > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> 
> I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.

Thanks to your reply! Could you please share the code ? And I will try to train the model to see the performance.

**Comment by shenqildr** [comment]
> > > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > > The error is due to the version mismatch of Pytorch.
> > > > If the given link resolves the issue then, please let me know.
> > > 
> > > 
> > > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> > 
> > 
> > I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.
> 
> Thanks to your reply! Could you please share the code ? And I will try to train the model to see the performance.

You can search for computing chamfer in github, there are many implementations of pytorch.

**Comment by wzm2256** [comment]
> > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > The error is due to the version mismatch of Pytorch.
> > > If the given link resolves the issue then, please let me know.
> > 
> > 
> > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> 
> I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.

Hi, did you try to use the EMD loss? I guess the EMD loss will produce better results.

**Comment by Yellowshuohahaha** [comment]
It seems didn't provide the EMDloss? I see the paper says the EMDloss can produce better results, but I havn't try it.

**Comment by Yellowshuohahaha** [comment]
> > > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > > The error is due to the version mismatch of Pytorch.
> > > > If the given link resolves the issue then, please let me know.
> > > 
> > > 
> > > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> > 
> > 
> > I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.
> 
> Hi, did you try to use the EMD loss? I guess the EMD loss will produce better results.

It seems didn't provide the EMDloss? I see the paper says the EMDloss can produce better results, but I havn't try it.

**Comment by wzm2256** [comment]
> > > > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > > > The error is due to the version mismatch of Pytorch.
> > > > > If the given link resolves the issue then, please let me know.
> > > > 
> > > > 
> > > > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > > > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> > > 
> > > 
> > > I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.
> > 
> > 
> > Hi, did you try to use the EMD loss? I guess the EMD loss will produce better results.
> 
> It seems didn't provide the EMDloss? I see the paper says the EMDloss can produce better results, but I havn't try it.

It seems to include a EMD loss: https://github.com/vinits5/pcrnet_pytorch/blob/master/pcrnet/losses/emd.py as a stand alone package that requries installation.

I might be able to test the code in one or two weeks. I will share the result then.

**Comment by Yellowshuohahaha** [comment]
> > > > > > Hey Yellowshuohahaha, I recommend you to take a look at this [link](https://github.com/junfu1115/DANet/issues/70).
> > > > > > The error is due to the version mismatch of Pytorch.
> > > > > > If the given link resolves the issue then, please let me know.
> > > > > 
> > > > > 
> > > > > The problem seems to be solved. But there is another error... I use pytorch 1.4, but it didn't work.
> > > > > ![image](https://user-images.githubusercontent.com/48409315/89660005-4ab92b80-d903-11ea-8d53-800300a5a5c3.png)
> > > > 
> > > > 
> > > > I have met the same problem. It seems that the chamfer distances function fails. So I rewrite the chamfer distances module by myself and it works. However, when I retrain the model it fails to reach the same performance as the pretrained model.
> > > 
> > > 
> > > Hi, did you try to use the EMD loss? I guess the EMD loss will produce better results.
> > 
> > 
> > It seems didn't provide the EMDloss? I see the paper says the EMDloss can produce better results, but I havn't try it.
> 
> It seems to include a EMD loss: https://github.com/vinits5/pcrnet_pytorch/blob/master/pcrnet/losses/emd.py as a stand alone package that requries installation.
> 
> I might be able to test the code in one or two weeks. I will share the result then.

That would be great! I test the code using chamsfer distance a month ago, but the result are not good. The two point clouds cannot be aligned very well, I will also use emdloss to try, thank you!

**Comment by wzm2256** [comment]
@Yellowshuohahaha Sorry for the delay.. I run the code several month ago, but I forgot to share my results.

In general, the model does not converge to the same results everytime, and you may want to see https://github.com/zhulf0804/PCReg.PyTorch for the numerical comparison.

I run the script with default settings, and one of the results is as follows:
![image](https://user-images.githubusercontent.com/24223188/107114446-d3a82400-68a0-11eb-87cc-cf611926b1a6.png)
It is clear to see a gradient explosion in around epoch 100.
It might be beneficial to use smaller learning rate than the default value.
