### ISSUE TITLE
The results res not good

### ISSUE THREAD

**Issue by zhangguanghui1** [vinits5/pcrnet_pytorch#9]
Following the code, I retrain the model via 'python train_pcrnet.py'. The loss curve is not good with Chamfer distance. I can not find the reason. Could you help me?
![image](https://user-images.githubusercontent.com/28031977/100311045-bc6bd100-2fe9-11eb-8296-f9077c5d60c7.png)

**Comment by vinits5** [comment]
Hey @zhangguanghui1,
Can you please check the visualizations of the 3D point clouds? Sometimes, the test loss might be unstable but the best_model has already learned to register 3D point clouds. 
I would highly recommend visualizing the source, template, and registered point cloud.
Thank you.
